# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180418_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=b'other', max_length=b'256', unique=True, verbose_name='username'),
        ),
    ]
