# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=b'other', max_length=255, verbose_name='username'),
        ),
    ]
