# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sense6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
